# makefile: makes thee pi program

# set the target name
all: BS_asian.exe

# compile the pi.cpp file
BS_asian.exe : BS_asian.cpp
	g++ BS_asian.cpp -o BS_asian.exe

# delete the exec file after execution?
clean :
	rm *.exe

